"""brand/mark.py - the logo mark, derived from the house piece.

The mark is the same house the hero renders (brand/house.py: body 2.30 x 1.80 x 1.45, ridge +0.84,
door wall on +X, blocks leaving through the door to +X), drawn in a flat isometric projection from
the same side the camera sees it: the long -Y wall on the left, the +X gable end with the doorway on
the right, one red block already out through the door. Four tones, nothing else. Whole-pixel
friendly at 32px, still the same shape at 320px.

    python brand/mark.py            writes assets/logo-mark.svg
"""
import pathlib, math

# house body, Blender units (brand/house.py)
HX, HY, HZ, RISE = 1.15, 0.90, 1.45, 0.84
# doorway on the +X wall: y range and height. Near the front corner, like the render.
DY0, DY1, DZ = -0.62, -0.12, 0.88
# the one red block, out through the door and lifting
BS = 0.56
BX0, BY0, BZ0 = 2.08, -0.50, 0.50

C30, S30 = math.cos(math.radians(30)), 0.5
def P(x, y, z):
    # visible faces: -Y (left) and +X (right); larger x - y is nearer the viewer
    return ((x + y) * C30, (x - y) * S30 - z)

def poly(pts):
    return [P(*p) for p in pts]

FACES = [
    # (tone, points) back to front
    ('roof', [(-HX, -HY, HZ), (HX, -HY, HZ), (HX, 0, HZ + RISE), (-HX, 0, HZ + RISE)]),
    ('wall', [(-HX, -HY, 0), (HX, -HY, 0), (HX, -HY, HZ), (-HX, -HY, HZ)]),
    ('end',  [(HX, -HY, 0), (HX, DY0, 0), (HX, DY0, DZ), (HX, DY1, DZ), (HX, DY1, 0), (HX, HY, 0),
              (HX, HY, HZ), (HX, 0, HZ + RISE), (HX, -HY, HZ)]),
    # the red block: top, left, right faces
    ('red-top',  [(BX0, BY0, BZ0 + BS), (BX0 + BS, BY0, BZ0 + BS), (BX0 + BS, BY0 + BS, BZ0 + BS), (BX0, BY0 + BS, BZ0 + BS)]),
    ('red-left', [(BX0, BY0, BZ0), (BX0 + BS, BY0, BZ0), (BX0 + BS, BY0, BZ0 + BS), (BX0, BY0, BZ0 + BS)]),
    ('red-right',[(BX0 + BS, BY0, BZ0), (BX0 + BS, BY0 + BS, BZ0), (BX0 + BS, BY0 + BS, BZ0 + BS), (BX0 + BS, BY0, BZ0 + BS)]),
]
TONE = {
    'roof': '#0E1420', 'wall': '#2A3040', 'end': '#1A1F2C',
    'red-top': '#CC3A34', 'red-left': '#B32A25', 'red-right': '#8C1F1B',
}

def build(size=32):
    pts = [p for _, f in FACES for p in poly(f)]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    w, h = max(xs) - min(xs), max(ys) - min(ys)
    s = (size - 2) / max(w, h)
    ox = 1 - min(xs) * s + (size - 2 - w * s) / 2
    oy = 1 - min(ys) * s + (size - 2 - h * s) / 2
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" width="{size}" height="{size}" role="img" aria-label="Hero\'s Junk Removal">',
           '  <!-- The house from the hero piece, flattened. Same body, same door wall, one block already out.',
           '       Generated by brand/mark.py from the house dimensions in brand/house.py; do not hand-edit. -->']
    for tone, face in FACES:
        d = ' '.join(f'{"M" if i == 0 else "L"}{x * s + ox:.2f} {y * s + oy:.2f}' for i, (x, y) in enumerate(poly(face))) + 'Z'
        out.append(f'  <path fill="{TONE[tone]}" d="{d}"/>')
    out.append('</svg>')
    return '\n'.join(out) + '\n'

if __name__ == '__main__':
    root = pathlib.Path(__file__).resolve().parent.parent
    svg = build(32)
    (root / 'assets' / 'logo-mark.svg').write_text(svg, encoding='utf-8')
    print(svg)
